-- ===== Esquema de Supabase para el Planificador Boda M & A =====
-- Ejecuta esto en el editor SQL de tu proyecto de Supabase.

create table if not exists public.activities (
  id          bigint generated by default as identity primary key,
  title       text not null,
  description text default '',
  due_date    date,
  status      text not null default 'pendiente'
              check (status in ('pendiente', 'en_proceso', 'finalizado')),
  created_at  timestamptz not null default now(),
  updated_at  timestamptz not null default now()
);

-- Índices útiles
create index if not exists activities_due_date_idx on public.activities (due_date);
create index if not exists activities_status_idx   on public.activities (status);

-- ---------------------------------------------------------------------------
-- Seguridad (RLS). La app usa la "anon key" y accede vía la API REST.
-- Para una app privada de la pareja, lo más simple es permitir todo a anon.
-- Ajusta a tu gusto si quieres restringir.
alter table public.activities enable row level security;

create policy "actividades: lectura pública"
  on public.activities for select using (true);

create policy "actividades: insertar"
  on public.activities for insert with check (true);

create policy "actividades: actualizar"
  on public.activities for update using (true) with check (true);

create policy "actividades: eliminar"
  on public.activities for delete using (true);
